version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: test_prefix_search
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
