version: '3.1'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
